version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql-debian
    hostname: db
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    #restart: always
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    tty: true
    stdin_open: true
    networks:
      - app-net
  back:
    container_name: plus-back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
    - "50000:8000"
    #restart: always
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./back/plus_back/
        target: /var/plus_back/
    depends_on:
      - mysql
    networks:
      - app-net
  socket:
    container_name: plus-socket
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
    - "50001:8080"
    #restart: always
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./socket/plus_socket/
        target: /var/plus_socket/
    networks:
      - app-net
  clinic:
    container_name: plus-clinic
    build:
      context: ./clinic
      dockerfile: Dockerfile
    ports:
    - "50002:8080"
    #restart: always
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./clinic/plus_clinic/
        target: /var/plus_clinic/
    networks:
      - app-net
#  net:
#    image: node:16-alpine
#    container_name: plus-net
#    ports:
#    - "50003:8080"
#    #restart: always
#    tty: true
#    stdin_open: true
#    volumes:
#      - ./net/plus_net:/var/plus_net
networks:
  app-net:
    driver: bridge